version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle_xe_telecom
    environment:
      - ORACLE_PASSWORD=12345
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init_scripts:/container-entrypoint-initdb.d/

volumes:
  oracle-data: