CREATE TABLE TARIFFS (
    TARIFF_ID INT PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    MONTHLY_FEE DECIMAL(10, 2),
    DATA_LIMIT INT,
    MINUTE_LIMIT INT,
    SMS_LIMIT INT
);
CREATE INDEX idx_tariff_name ON TARIFFS(NAME);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    NAME VARCHAR2(100),
    CITY VARCHAR2(100),
    SIGNUP_DATE DATE,
    TARIFF_ID INT,
    CONSTRAINT fk_customer_tariff FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS(TARIFF_ID)
);
CREATE INDEX idx_customers_city ON CUSTOMERS(CITY);
CREATE INDEX idx_customers_tariff_id ON CUSTOMERS(TARIFF_ID);

CREATE TABLE MONTHLY_STATS (
    ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    DATA_USAGE DECIMAL(10, 2), 
    MINUTE_USAGE INT,
    SMS_USAGE INT,
    PAYMENT_STATUS VARCHAR2(20),
    CONSTRAINT fk_stats_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);
CREATE INDEX idx_stats_payment_status ON MONTHLY_STATS(PAYMENT_STATUS);
CREATE INDEX idx_stats_customer_id ON MONTHLY_STATS(CUSTOMER_ID);